version: '3'

services:
  frontend:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./modules/frontend:/usr/share/nginx/html

  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    volumes:
      - ./var/postgis_data:/var/lib/postgresql
      - ./docker/postgis/pg_hba.conf:/etc/postgresql/10/main/pg_hba.conf.template
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=simtanah

  geoserver:
    image: kartoza/geoserver:2.13.0
    ports:
      - 9090:8080
    volumes:
      - ./var/geoserver_data:/opt/geoserver/data_dir
      - ./docker/geoserver/web.xml:/usr/local/tomcat/conf/web.xml
    restart: on-failure
    depends_on:
      - postgis
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  api:
    image: nginx:stable-alpine
    ports:
      - 8081:80
    links:
      - php
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./modules/api:/app

  php:
    build: ./docker/php
    image: php:simtanah
    ports:
      - 9000:9000
    volumes:
      - ./modules/api:/app
      - ./docker/php/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini

  pictshare:
    image: hascheksolutions/pictshare
    ports:
      - 8082:80
    volumes:
      - ./docker/nginx/pictshare.conf:/etc/nginx/conf.d/default.conf
      - ./var/pictshare_data:/usr/share/nginx/html/upload
