version: '3'
services:
  frontend:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/usr/share/nginx/html
  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    volumes:
      - ./postgis_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=simtanah
