version: '3'

services:
  frontend:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./modules/frontend:/usr/share/nginx/html

  postgis:
    image: mdillon/postgis:10-alpine
    ports:
      - 5432:5432
    volumes:
      - ./var/postgis_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  pgadmin:
    image: dpage/pgadmin4:3.5
    links:
      - postgis
    ports:
      - 8083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD

  geoserver:
    image: kartoza/geoserver:2.13.0
    ports:
      - 9090:8080
    volumes:
      - ./var/geoserver_data:/opt/geoserver/data_dir
      - ./docker/geoserver/web.xml:/usr/local/tomcat/conf/web.xml
    restart: on-failure
    depends_on:
      - postgis
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  api:
    image: nginx:stable-alpine
    ports:
      - 8081:80
    links:
      - php
      - postgis
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./modules/api:/app

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.prod
    image: php:simtanah-prod
    ports:
      - 9000:9000
    volumes:
      - ./modules/api:/app
      - ./docker/php/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini
